from pathlib import Path
import os
import pandas as pd
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches,Pt,RGBColor

REPO_ROOT=Path(__file__).resolve().parents[2];SOURCE=Path(os.environ.get('IPM_DATA_ROOT',REPO_ROOT/'data')).resolve();R=SOURCE/'RSA_multimodal_geometry'
d=Document();s=d.sections[0];s.top_margin=s.bottom_margin=s.left_margin=s.right_margin=Inches(1)
n=d.styles['Normal'];n.font.name='Calibri';n.font.size=Pt(11);n.paragraph_format.space_after=Pt(8);n.paragraph_format.line_spacing=1.25
for k,z in [('Heading 1',16),('Heading 2',13)]:d.styles[k].font.name='Calibri';d.styles[k].font.size=Pt(z);d.styles[k].font.color.rgb=RGBColor(31,77,120)
p=d.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run('Final Decision Report\nTime-Resolved Multimodal Representational Similarity Analysis');r.bold=True;r.font.size=Pt(20);r.font.color.rgb=RGBColor(31,77,120)
d.add_heading('Decision',1);p=d.add_paragraph();p.add_run('Gate A was not passed. Do not generate or submit a CHB multimodal RSA manuscript from the present analysis.').bold=True
d.add_heading('Verified sample flow',1);d.add_paragraph('The recorded study sample contains 30 participants. Behavioral and eye-tracking inventories retain all 30. The s5 EEG file exists but contains only four epochs and cannot cover the four identities and 16 editing conditions. Applying the prespecified odd/even repetition coverage requirement produced 21 participants for the strict all-channel crossnobis analysis. Exclusions were based on condition/partition coverage rather than observed RSA results.')
d.add_heading('Primary analysis',1);d.add_paragraph('EEG–Naturalness unique representational correspondence produced a 140–340 ms cluster that survived the joint time × four-primary-contrast max-cluster correction (p = .0384). EEG–Gaze, EEG–Beauty, and the direct Beauty-minus-Naturalness coefficient did not yield a jointly corrected cluster. Thus only one Gate criterion was met, whereas Gate A requires at least two and at least one credible cross-modal result.')
d.add_heading('Robustness and negative controls',1);d.add_paragraph('Shuffled Beauty and shuffled Naturalness label controls were null (p = .511 and .848). However, mismatching each participant’s EEG with another participant’s Gaze RDM remained significant (p = .00139). This indicates that shared design-level condition geometry can generate apparent Gaze–EEG correspondence and prevents an individual-specific cross-modal interpretation. The Naturalness coefficient was positive under most identity deletions but weakened markedly when F1 was removed, so identity robustness is incomplete. Aggregating 20-ms windows into 40-ms windows preserved direction but does not create independent evidence.')
d.add_heading('Interpretation',1);d.add_paragraph('The defensible result is a provisional time-resolved correspondence between EEG condition geometry and Naturalness geometry after controlling the four edit-factor RDMs. It is not sufficient evidence for shared Gaze–neural representations, a Beauty–Naturalness representational dissociation, causal mediation, or cross-identity generalization. Findings remain limited to the four identities and current editing operations.')
d.add_heading('Publication decision',1);d.add_paragraph('The current evidence does not support a CHB multimodal representational-alignment paper. The EEG–Naturalness result may be retained as an exploratory specialist EEG finding, but it requires replication, stronger image-RDM controls, alternative distance specifications, and independent identities before being framed as a primary representational claim.')
d.add_heading('Claims that must not be written',1);d.add_paragraph('Do not claim that gaze causes or mediates EEG; that Beauty and Naturalness have demonstrably different neural geometries; that the four identities establish population-level cross-face generalization; that RSA proves identical codes; or that these data explain real-world filter use, well-being, authenticity detection, or AI detection.')
d.add_heading('Ethics statement confirmed by the author',1);d.add_paragraph('This study was conducted in accordance with the Declaration of Helsinki and was approved by the Institutional Board of Sichuan University (Ref. No. YJ202203). Informed consent was obtained from all participants involved in the study.')
d.add_heading('Prior-publication boundary',1);d.add_paragraph('Any later use must remain distinct from the published eye-tracking and N170 papers. Simple AOI–rating associations, the N170 factorial result, and earlier linear cascade/prediction findings must not be repackaged as RSA discoveries.')
d.save(R/'RSA_Final_Decision_Report.docx')
